#!/usr/bin/env bash

if [ ! -f install ]; then
    echo 'install must be run within its container folder' 1>&2
    exit 1
fi

CURDIR=`pwd`
OLDGOPATH="$GOPATH"
export GOPATH="$CURDIR"

gofmt -w src

go install upload

export GOPATH="$OLDGOPATH"

cp bin/upload /usr/local/bin/
cp init/upload.service /etc/systemd/system/

echo 'finished'
